name: example
description: Demonstrates how to use the image_watermark plugin.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=2.19.0-317.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_watermark: 
    # When depending on this package from a real application you should use:
    #   image_watermark: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  image_picker: ^0.8.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
