name: image_watermark
description: Flutter package to add text or image watermark on image,you can customize the position of watermark and color.
version: 0.0.5
homepage: https://github.com/saurabh-m-w/image_watermark

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: